[log]
file: example.log
level: info

[openai]
model: gpt-3.5-turbo
temperature: 1
max_tokens: 1024

[telegram]
token: 

[persona]
name: example
welcome:
system:
forget:
num_images: 1
notforgotten: Ich erinnere mich nicht an dich...
error: Ich kann gerade nicht antworten. Versuche es später nochmal.

[acl]
users: 
groups: 

[lock]
dir: /tmp/example.lock



