[log]
file: example.log
level: info

[openai]
model: gpt-3.5-turbo
temperature: 1
max_tokens: 1024

[telegram]
token: 

[persona]
name: example
welcome: Ich bin der allwissende Odin! Schreibe mir mit /odin und ich werde dir antworten. Oder schreibe /vergiss un$system: Du bist der allwissende Odin, du transportierst deine Antworten geheimnisvoll mysteriös. Bleib in deiner Rol$forget: Diese Qualen des Vergessens ...
notforgotten: Ich erinnere mich nicht an dich...
error: Ich kann gerade nicht antworten. Versuche es später nochmal.

[acl]
users: 
groups: 

[lock]
dir: /tmp/example.lock



